services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d

  webgoat:
    image: webgoat/webgoat:latest
    container_name: webgoat
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "9090:9090"
    environment:
      TZ: America/Boise
    tty: true
    command: /bin/bash -c webgoat/webgoat
