services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mitre_db
      POSTGRES_USER: mitre_admin
      POSTGRES_PASSWORD: changeme
      ADMIN_USER_EMAIL: $MITRE_TRAINING_PLATFORM_ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
  webgoat:
    image: webgoat/webgoat:v2023.8
    container_name: webgoat
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "9090:9090"
    environment:
      TZ: America/Boise
    tty: true
    volumes:
      - wg_data:/home/webgoat
    command: /bin/bash -c webgoat/webgoat
  web-app:
    build: .
    container_name: web-app
    restart: unless-stopped
    environment:
      ADMIN_USER_EMAIL: $MITRE_TRAINING_PLATFORM_ADMIN_EMAIL
    ports:
      - "3000:3000"
volumes:
  wg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./webgoat_data
